# Generated by Django 3.2.9 on 2021-11-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonkey', models.IntegerField(verbose_name='event_id')),
                ('full_name', models.TextField(verbose_name='event_full_name')),
                ('url', models.URLField(verbose_name='event_url')),
                ('team1', models.CharField(max_length=100, verbose_name='team1')),
                ('team2', models.CharField(max_length=100, verbose_name='team2')),
                ('score1', models.IntegerField(verbose_name='score1')),
                ('score2', models.IntegerField(verbose_name='score2')),
                ('score_comment', models.CharField(max_length=255, verbose_name='comment')),
                ('is_live', models.BooleanField(verbose_name='is_live')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='is_blocked')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonkey', models.IntegerField(choices=[(921, 'win1'), (3150, 'win1'), (3144, 'win1'), (922, 'draw'), (3152, 'draw'), (923, 'win2'), (3151, 'win2'), (3145, 'win2'), (924, 'win1draw'), (1571, 'notDraw'), (925, 'win2draw'), (927, 'fora1'), (937, 'fora1'), (1845, 'fora1'), (928, 'fora2'), (938, 'fora2'), (1846, 'fora2'), (930, 'totalOver'), (940, 'totalOver'), (1848, 'totalOver'), (931, 'totalUnder'), (941, 'totalUnder'), (1849, 'totalUnder')], verbose_name='factor_name')),
                ('param', models.IntegerField(verbose_name='param_value')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='value')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='is_blocked')),
            ],
        ),
        migrations.CreateModel(
            name='SportSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonkey', models.IntegerField(verbose_name='segment_id')),
                ('name', models.CharField(max_length=255, verbose_name='segment_name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='SportKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonkey', models.IntegerField(verbose_name='sport_id')),
                ('name', models.CharField(max_length=255, verbose_name='sport_name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sportsegment')),
            ],
        ),
        migrations.CreateModel(
            name='EventSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonkey', models.IntegerField(verbose_name='event_segment_id')),
                ('name', models.CharField(max_length=255, verbose_name='event_segment_name')),
                ('is_blocked', models.BooleanField(default='False', verbose_name='is_blocked')),
                ('factors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factor')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='factors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factor'),
        ),
        migrations.AddField(
            model_name='event',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventsegment'),
        ),
    ]
