# Generated by Django 3.2.9 on 2021-11-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.sportsegment'),
        ),
        migrations.AlterField(
            model_name='eventsegment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='main.event'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='main.event'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='event_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='main.eventsegment'),
        ),
        migrations.AlterField(
            model_name='sportsegment',
            name='sport_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='main.sportkind'),
        ),
    ]
