# Generated by Django 3.2.9 on 2021-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eventsegment_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsegment',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='is_live'),
        ),
    ]
