# Generated by Django 3.2.9 on 2021-11-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_eventsegment_factors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='factors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.factor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eventsegment'),
        ),
        migrations.AlterField(
            model_name='sportkind',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sportsegment'),
        ),
        migrations.AlterField(
            model_name='sportsegment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
