# Generated by Django 3.2.9 on 2021-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211121_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsegment',
            name='score_comment',
            field=models.CharField(max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_comment',
            field=models.CharField(max_length=255, null=True, verbose_name='comment'),
        ),
    ]
