# Generated by Django 3.2.9 on 2021-11-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211121_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='param',
            field=models.IntegerField(null=True, verbose_name='param_value'),
        ),
    ]
