# Generated by Django 3.2.9 on 2021-11-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_factor_param'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='block_time')),
                ('factor_name', models.CharField(max_length=1024, verbose_name='factor_name')),
                ('factor_param', models.IntegerField(null=True, verbose_name='factor_param')),
                ('factor_value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='factor_value')),
                ('score', models.CharField(max_length=255, verbose_name='score')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.event')),
                ('event_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.eventsegment')),
            ],
        ),
    ]
